<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Análisis Multivariado | Manual de Construcción de Índices Compuestos</title>
  <meta name="description" content="Guía práctica para crear índices compuestos con R" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Análisis Multivariado | Manual de Construcción de Índices Compuestos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Guía práctica para crear índices compuestos con R" />
  <meta name="github-repo" content="lesflores/composite_indicator_r" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Análisis Multivariado | Manual de Construcción de Índices Compuestos" />
  
  <meta name="twitter:description" content="Guía práctica para crear índices compuestos con R" />
  

<meta name="author" content="Lesly Estefania Flores Rivera" />


<meta name="date" content="2023-01-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="imputación-de-datos-faltantes.html"/>
<link rel="next" href="normalización.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Índices Compuestos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Sobre este Manual</a></li>
<li class="chapter" data-level="2" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>2</b> Introducción</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introducción.html"><a href="introducción.html#datos-ficticios-para-la-construcción-del-índice-compuesto"><i class="fa fa-check"></i><b>2.1</b> Datos Ficticios para la Construcción del Índice Compuesto</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="imputación-de-datos-faltantes.html"><a href="imputación-de-datos-faltantes.html"><i class="fa fa-check"></i><b>3</b> Imputación de Datos Faltantes</a>
<ul>
<li class="chapter" data-level="3.1" data-path="imputación-de-datos-faltantes.html"><a href="imputación-de-datos-faltantes.html#imputación-por-media-y-moda"><i class="fa fa-check"></i><b>3.1</b> Imputación por Media y Moda</a></li>
<li class="chapter" data-level="3.2" data-path="imputación-de-datos-faltantes.html"><a href="imputación-de-datos-faltantes.html#imputación-por-modelos-de-regresión"><i class="fa fa-check"></i><b>3.2</b> Imputación por Modelos de Regresión</a></li>
<li class="chapter" data-level="3.3" data-path="imputación-de-datos-faltantes.html"><a href="imputación-de-datos-faltantes.html#paquete-amelia"><i class="fa fa-check"></i><b>3.3</b> Paquete Amelia</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-multivariado.html"><a href="análisis-multivariado.html"><i class="fa fa-check"></i><b>4</b> Análisis Multivariado</a>
<ul>
<li class="chapter" data-level="4.1" data-path="análisis-multivariado.html"><a href="análisis-multivariado.html#análisis-factorial-para-datos-mixtos"><i class="fa fa-check"></i><b>4.1</b> Análisis Factorial para Datos Mixtos</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="normalización.html"><a href="normalización.html"><i class="fa fa-check"></i><b>5</b> Normalización</a></li>
<li class="chapter" data-level="6" data-path="selección-de-variables.html"><a href="selección-de-variables.html"><i class="fa fa-check"></i><b>6</b> Selección de Variables</a></li>
<li class="chapter" data-level="7" data-path="ponderación-y-agregación.html"><a href="ponderación-y-agregación.html"><i class="fa fa-check"></i><b>7</b> Ponderación y Agregación</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ponderación-y-agregación.html"><a href="ponderación-y-agregación.html#enfoque-1-inclusión-de-todas-las-variables"><i class="fa fa-check"></i><b>7.1</b> Enfoque 1: Inclusión de todas las Variables</a></li>
<li class="chapter" data-level="7.2" data-path="ponderación-y-agregación.html"><a href="ponderación-y-agregación.html#enfoque-2-selección-de-las-variables-más-significativas-identificadas-en-el-famd"><i class="fa fa-check"></i><b>7.2</b> Enfoque 2: Selección de las variables más significativas identificadas en el FAMD</a></li>
<li class="chapter" data-level="7.3" data-path="ponderación-y-agregación.html"><a href="ponderación-y-agregación.html#enfoque-3-varianza-explicativa-famd"><i class="fa fa-check"></i><b>7.3</b> Enfoque 3: Varianza Explicativa FAMD</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="validación.html"><a href="validación.html"><i class="fa fa-check"></i><b>8</b> Validación</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Manual de Construcción de Índices Compuestos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-multivariado" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Capítulo 4</span> Análisis Multivariado<a href="análisis-multivariado.html#análisis-multivariado" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En la construcción de índices compuestos, técnicas de reducción de dimensionalidad como el Análisis de Componentes Principales (ACP) para variables cuantitativas y el Análisis de Correspondencias Múltiples (ACM) para variables cualitativas se emplean para sintetizar la información de múltiples variables. Estas técnicas extraen dimensiones principales que capturan la mayor variabilidad posible de los datos. Para conjuntos de datos que contienen tanto variables cuantitativas como cualitativas, se recomienda el Análisis Factorial para Datos Mixtos (FAMD), que combina los principios del ACP y ACM en un solo marco de análisis. Esta técnica permite analizar simultáneamente ambos tipos de variables y descubrir estructuras subyacentes en el conjunto de datos.</p>
<div id="análisis-factorial-para-datos-mixtos" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Análisis Factorial para Datos Mixtos<a href="análisis-multivariado.html#análisis-factorial-para-datos-mixtos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cuando se trabaja con conjuntos de datos mixtos que incluyen tanto variables continuas como categóricas, es recomendable utilizar el <em>Análisis Factorial para Datos Mixtos</em> (FAMD), en R, este análisis se puede realizar mediante el paquete <code>FactoMineR</code> y <code>factoextra</code> <span class="citation">(<a href="#ref-pages2004">Pages 2004</a>)</span>. Para mayor información sobre FAMD véase también a <span class="citation">(<a href="#ref-Le2008">Lê 2008</a>)</span>.</p>
<p>En este código de R, convertimos las variables <code>Funcionarias_electas</code> y <code>Sufragio</code> en factores, que es necesario para el FAMD, asignándoles etiquetas para representar las categorías binarias. Luego, ejecutamos el FAMD en los datos, omitiendo la primera columna que contiene el nombre de los planetas.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="análisis-multivariado.html#cb6-1" tabindex="-1"></a><span class="co"># FactoMineR</span></span>
<span id="cb6-2"><a href="análisis-multivariado.html#cb6-2" tabindex="-1"></a><span class="fu">library</span>(FactoMineR)</span>
<span id="cb6-3"><a href="análisis-multivariado.html#cb6-3" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb6-4"><a href="análisis-multivariado.html#cb6-4" tabindex="-1"></a></span>
<span id="cb6-5"><a href="análisis-multivariado.html#cb6-5" tabindex="-1"></a><span class="co"># Convertir las columnas binarias en factores (las variables cualitativas deben ser factores en FAMD)</span></span>
<span id="cb6-6"><a href="análisis-multivariado.html#cb6-6" tabindex="-1"></a>datos_IST_imputados_3<span class="sc">$</span>Funcionarias_electas <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb6-7"><a href="análisis-multivariado.html#cb6-7" tabindex="-1"></a>  datos_IST_imputados_3<span class="sc">$</span>Funcionarias_electas, </span>
<span id="cb6-8"><a href="análisis-multivariado.html#cb6-8" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb6-9"><a href="análisis-multivariado.html#cb6-9" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No_Funcionarias&quot;</span>, <span class="st">&quot;Sí_Funcionarias&quot;</span>)</span>
<span id="cb6-10"><a href="análisis-multivariado.html#cb6-10" tabindex="-1"></a>)</span>
<span id="cb6-11"><a href="análisis-multivariado.html#cb6-11" tabindex="-1"></a></span>
<span id="cb6-12"><a href="análisis-multivariado.html#cb6-12" tabindex="-1"></a>datos_IST_imputados_3<span class="sc">$</span>Sufragio <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb6-13"><a href="análisis-multivariado.html#cb6-13" tabindex="-1"></a>  datos_IST_imputados_3<span class="sc">$</span>Sufragio, </span>
<span id="cb6-14"><a href="análisis-multivariado.html#cb6-14" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb6-15"><a href="análisis-multivariado.html#cb6-15" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No_Sufragio&quot;</span>, <span class="st">&quot;Sí_Sufragio&quot;</span>)</span>
<span id="cb6-16"><a href="análisis-multivariado.html#cb6-16" tabindex="-1"></a>)</span>
<span id="cb6-17"><a href="análisis-multivariado.html#cb6-17" tabindex="-1"></a></span>
<span id="cb6-18"><a href="análisis-multivariado.html#cb6-18" tabindex="-1"></a><span class="co"># FAMD</span></span>
<span id="cb6-19"><a href="análisis-multivariado.html#cb6-19" tabindex="-1"></a></span>
<span id="cb6-20"><a href="análisis-multivariado.html#cb6-20" tabindex="-1"></a>famd <span class="ot">&lt;-</span> <span class="fu">FAMD</span>(datos_IST_imputados_3 [,<span class="sc">-</span><span class="dv">1</span>], <span class="at">graph =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Los dos códigos siguientes de R se utilizan para mostrar los valores propios (en tabla y scree plot), también conocidos como <code>eigenvalues</code>, de un análisis FAMD almacenado previamente en el objeto <code>famd</code>. Los valores propios son importantes porque nos indican la cantidad de varianza explicada por cada dimensión del análisis FAMD.</p>
<p>Usualmente se elige un conjunto de dimensiones que explique entre el 70 y 80% de la varianza. A modo de ejemplo, si se escogen las dos primeras dimensiones, estas suman el <code>75.776%</code> de la varianza.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="análisis-multivariado.html#cb7-1" tabindex="-1"></a><span class="co"># eigenvalues (valores propios)</span></span>
<span id="cb7-2"><a href="análisis-multivariado.html#cb7-2" tabindex="-1"></a>eigenvalues <span class="ot">&lt;-</span> <span class="fu">get_eigenvalue</span>(famd)</span>
<span id="cb7-3"><a href="análisis-multivariado.html#cb7-3" tabindex="-1"></a>eigenvalues</span></code></pre></div>
<pre><code>##       eigenvalue variance.percent cumulative.variance.percent
## Dim.1 2.10809159       42.1618318                    42.16183
## Dim.2 1.68071357       33.6142713                    75.77610
## Dim.3 0.99947430       19.9894859                    95.76559
## Dim.4 0.16204539        3.2409078                    99.00650
## Dim.5 0.04967516        0.9935032                   100.00000</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="análisis-multivariado.html#cb9-1" tabindex="-1"></a><span class="co"># Gráfico eigenvalues (valores propios)</span></span>
<span id="cb9-2"><a href="análisis-multivariado.html#cb9-2" tabindex="-1"></a><span class="fu">fviz_eig</span>(famd)</span></code></pre></div>
<p><img src="figures/unnamed-chunk-13-1.png" width="672" /></p>
<p>En el siguiente código en R, se aplicó la función <code>fviz_famd_var</code> para generar un gráfico (variables - FAMD) que visualiza la posición de las variables en un análisis FAMD. La posición de las variables en el gráfico ayuda a comprender su contribución a la estructura de los datos.</p>
<p>El eje horizontal (Dim1) representa la primera dimensión y explica el 42.2% de la variabilidad en los datos, mientras que el eje vertical (Dim2) representa la segunda dimensión y explica el 33.6%. Los puntos rojos indican la posición de cada variable en estas dos dimensiones. <code>Libertad_asociacion</code> y <code>Elecciones_limpias</code> tienen una fuerte asociación con la primera dimensión. <code>Funcionarias_electas</code> está más relacionada con la segunda dimensión.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="análisis-multivariado.html#cb10-1" tabindex="-1"></a><span class="co"># Gráfico de las variables en el plano factorial</span></span>
<span id="cb10-2"><a href="análisis-multivariado.html#cb10-2" tabindex="-1"></a><span class="fu">fviz_famd_var</span>(famd, <span class="at">choice =</span> <span class="st">&quot;var&quot;</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="figures/unnamed-chunk-14-1.png" width="672" /></p>
<p>En el siguiente código en R, se aplicó la función <code>fviz_famd_ind</code> para generar el gráfico individuals - FAMD. Este gráfico representa la dispersión de las observaciones, cada punto corresponde a un planeta, ubicado de acuerdo con los valores que toma en las dos dimensiones consideradas más explicativas de la variabilidad en los datos. Por ejemplo, los planetas marcados con 1 y 6 están cerca en el espacio de la dimensión, lo que indica que tienen perfiles similares en términos de las variables estudiadas. Por otro lado, los planetas que están más alejados en el gráfico, como los puntos 10 y 7, tendrían características distintas.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="análisis-multivariado.html#cb11-1" tabindex="-1"></a><span class="co"># Gráfico eigenvalues (valores propios)</span></span>
<span id="cb11-2"><a href="análisis-multivariado.html#cb11-2" tabindex="-1"></a><span class="fu">fviz_famd_ind</span>(famd, <span class="at">invisible =</span> <span class="st">&quot;quali.var&quot;</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="figures/unnamed-chunk-15-1.png" width="672" /></p>
<p>En el siguiente código en R, se aplicó la función <code>fviz_contrib</code> para generar el gráfico Contribution of variables to Dim-1. El gráfico muestra cómo cada variable influye en la primera dimensión del FAMD. <code>Libertad_asociacion</code> y <code>Libertad_expresion</code> son las más influyentes, mientras que <code>Funcionarias_electas</code> contribuye menos.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="análisis-multivariado.html#cb12-1" tabindex="-1"></a><span class="co"># Contribución de las variables a la dim 1</span></span>
<span id="cb12-2"><a href="análisis-multivariado.html#cb12-2" tabindex="-1"></a><span class="fu">fviz_contrib</span>(famd, <span class="at">choice =</span> <span class="st">&quot;var&quot;</span>, <span class="at">axes =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="figures/unnamed-chunk-16-1.png" width="672" /></p>
<p>En el siguiente fragmento de código R, se utilizó de nuevo la función <code>fviz_contrib</code>, en esta ocasión para destacar las contribuciones de las variables a la segunda dimensión del análisis FAMD. Este gráfico muestra que <code>Sufragio</code> domina esta dimensión.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="análisis-multivariado.html#cb13-1" tabindex="-1"></a><span class="co"># Contribución de las variables a la dim 2</span></span>
<span id="cb13-2"><a href="análisis-multivariado.html#cb13-2" tabindex="-1"></a><span class="fu">fviz_contrib</span>(famd, <span class="at">choice =</span> <span class="st">&quot;var&quot;</span>, <span class="at">axes =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="figures/unnamed-chunk-17-1.png" width="672" /></p>
<p>El FAMD es útil para identificar las variables como <code>Libertad_asociacion</code>, <code>Libertad_expresion</code> y <code>Sufragio</code>, en función de su aporte a las principales dimensiones del análisis. Además, permite examinar cómo cada observación (Planetas) se relaciona con estas dimensiones a través de sus puntuaciones, que pueden ser visualizadas con la función <code>fviz_famd_ind</code>, facilitando la integración de estas relaciones en el índice compuesto.</p>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Le2008" class="csl-entry">
Lê, Josse, S. 2008. <em>FactoMineR: An r Package for Multivariate Analysis.</em> <em>Journal of Statistical Software</em>. Vol. 25.
</div>
<div id="ref-pages2004" class="csl-entry">
Pages, J. 2004. <em>Analyse Factorielle de Donnees Mixtes</em>. <em>Revue Statistique Appliquee</em>. Vol. 4.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="imputación-de-datos-faltantes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="normalización.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/index.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
